spring.application.name=Portfolio
spring.mail.host=smtp.gmail.com
spring.mail.port=587

server.port=1010

spring.mail.username=mosewadesmond919@gmail.com
spring.mail.password=ghmuydizpdbczvij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
